/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreasurerRouteImport } from './routes/treasurer'
import { Route as IndexRouteImport } from './routes/index'

const TreasurerRoute = TreasurerRouteImport.update({
  id: '/treasurer',
  path: '/treasurer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/treasurer': typeof TreasurerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/treasurer': typeof TreasurerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/treasurer': typeof TreasurerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/treasurer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/treasurer'
  id: '__root__' | '/' | '/treasurer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TreasurerRoute: typeof TreasurerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treasurer': {
      id: '/treasurer'
      path: '/treasurer'
      fullPath: '/treasurer'
      preLoaderRoute: typeof TreasurerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TreasurerRoute: TreasurerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
